// Code generated by sqlc. DO NOT EDIT.
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
	first_name,
	last_name,
	email_address,
	gender,
	age,
	height,
	current_weight
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
) RETURNING id, first_name, last_name, email_address, gender, age, height, current_weight, created_at
`

type CreateAccountParams struct {
	FirstName     sql.NullString `json:"first_name"`
	LastName      string         `json:"last_name"`
	EmailAddress  string         `json:"email_address"`
	Gender        string         `json:"gender"`
	Age           int32          `json:"age"`
	Height        int32          `json:"height"`
	CurrentWeight int32          `json:"current_weight"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddress,
		arg.Gender,
		arg.Age,
		arg.Height,
		arg.CurrentWeight,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailAddress,
		&i.Gender,
		&i.Age,
		&i.Height,
		&i.CurrentWeight,
		&i.CreatedAt,
	)
	return i, err
}
