// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           int64          `json:"id"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     string         `json:"last_name"`
	EmailAddress string         `json:"email_address"`
	Gender       string         `json:"gender"`
	// must be positive
	Age int32 `json:"age"`
	// must be positive
	Height int32 `json:"height"`
	// must be positive
	CurrentWeight int32     `json:"current_weight"`
	CreatedAt     time.Time `json:"created_at"`
}

type Exercise struct {
	ID        int64          `json:"id"`
	AccountID sql.NullInt64  `json:"account_id"`
	StartTime sql.NullTime   `json:"start_time"`
	StopTime  sql.NullTime   `json:"stop_time"`
	Type      sql.NullString `json:"type"`
	// must be positive
	CaloriesBurned sql.NullInt32 `json:"calories_burned"`
	CreatedAt      time.Time     `json:"created_at"`
}

type Foodlog struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// must be positive
	Calories int32 `json:"calories"`
	// must be positive
	Protein int32 `json:"protein"`
	// must be positive
	Fat int32 `json:"fat"`
	// must be positive
	Carbs     int32     `json:"carbs"`
	CreatedAt time.Time `json:"created_at"`
}

type Macro struct {
	ID        int64         `json:"id"`
	AccountID sql.NullInt64 `json:"account_id"`
	// must be positive
	Protein int32 `json:"protein"`
	// must be positive
	Fats int32 `json:"fats"`
	// must be positive
	Carbs int32 `json:"carbs"`
	// must be positive
	Calories  int32     `json:"calories"`
	CreatedAt time.Time `json:"created_at"`
}
